name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]         # creates a GitHub Release on version tags
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Minimal global permissions; per-job overrides add what's needed
permissions:
  contents: read

concurrency:
  group: maven-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.resolver.transport=wagon -Dorg.slf4j.simpleLogger.showDateTime=true

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven validate
        run: mvn -B -ntp validate

      - name: Build (clean package)
        run: mvn -B -ntp clean package

      - name: Upload build artifacts (JARs)
        uses: actions/upload-artifact@v4
        with:
          name: jars-${{ github.run_number }}-${{ github.sha }}
          path: |
            **/target/*.jar
          if-no-files-found: error
          retention-days: 14

      - name: Upload test reports (Surefire/FailSafe)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ github.run_number }}-${{ github.sha }}
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload Maven logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: maven-logs-${{ github.run_number }}-${{ github.sha }}
          path: ~/.m2/repository/.cache/**/*
          if-no-files-found: ignore
          retention-days: 3

  dependency-graph:
    name: Submit dependency graph (non-blocking)
    runs-on: ubuntu-latest
    needs: build
    # Don’t fail the whole workflow if API is not available (403) or GHAS not enabled
    continue-on-error: true

    permissions:
      contents: read
      dependency-graph: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Submit dependency snapshot
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  release:
    name: Create GitHub Release (on tags)
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - name: Download JAR artifacts
        uses: actions/download-artifact@v4
        with:
          name: jars-${{ needs.build.result == 'success' && github.run_number || github.run_number }}-${{ github.sha }}
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            dist/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
