name: Java CI (Maven + Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write   # needed if you push to GHCR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Xmx1g -XX:+TieredCompilation -XX:TieredStopAtLevel=1
  JAVA_VERSION: '17'
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: maven

      - name: Validate and build (tests on)
        run: |
          mvn -B -ntp -U -DskipITs=true clean verify

      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: jars-${{ github.run_number }}-${{ github.sha }}
          path: |
            **/target/*.jar
          if-no-files-found: warn
          retention-days: 7

      - name: Upload test reports (Surefire/FailSafe)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ github.run_number }}-${{ github.sha }}
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
          if-no-files-found: ignore
          retention-days: 7

      - name: Submit dependency graph (Dependabot)
        if: ${{ github.event_name != 'pull_request' }}
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  docker:
    name: Build & (optionally) push Docker image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for Dockerfile
        id: df
        shell: bash
        run: |
          if [ -f Dockerfile ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
            echo "No Dockerfile found; skipping Docker build."
          fi

      - name: Set up QEMU (multi-arch, optional)
        if: ${{ steps.df.outputs.exists == 'true' }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ steps.df.outputs.exists == 'true' }}
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: ${{ steps.df.outputs.exists == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image (no push on PRs)
        if: ${{ steps.df.outputs.exists == 'true' && github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ env.DOCKER_IMAGE }}:pr-${{ github.event.number }}

      - name: Build & Push Docker image (main)
        if: ${{ steps.df.outputs.exists == 'true' && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.run_id }}
